### ISSUE TITLE
export bug?

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#59]
`pingy export` seems to compile all the files in the `node_modules` folder...

```
...
✔ Compiling assignInAll.js
✔ Compiling assignInAllWith.js
✔ Compiling assignInWith.js
✔ Compiling assignWith.js
✔ Compiling assoc.js
✔ Compiling assocPath.js
✔ Compiling at.js
✔ Compiling attempt.js
✔ Compiling before.js
✔ Compiling bind.js
✔ Compiling bindAll.js
✔ Compiling bindKey.js
✔ Compiling camelCase.js
✔ Compiling capitalize.js
✔ Compiling castArray.js
✔ Compiling ceil.js
✔ Compiling chain.js
✔ Compiling chunk.js
✔ Compiling clamp.js
✔ Compiling clone.js
✔ Compiling cloneDeep.js
✔ Compiling cloneDeepWith.js
✔ Compiling cloneWith.js
✔ Compiling collection.js
✔ Compiling commit.js
✔ Compiling compact.js
✔ Compiling complement.js
✔ Compiling compose.js
✔ Compiling concat.js
✔ Compiling cond.js
✔ Compiling conforms.js
...
```

and puts a 9.8MB `.sha.json` into the public folder.

Pingy version is 0.9.3, node is 8.4.0, on mac os 10.12.6.

this is the `.pingy.json`:

```
{
	"name": "xxx",
	"exportDir": "public",
	"minify": true,
	"compile": false,
	"exclusions": [
		{
			"path": "node_modules",
			"action": "exclude",
			"type": "dir"
		}
	],
	"port": 64410
}
```

**Comment by filtercake** [comment]
with it `compile: false`, as shown above it completes the export, but the scss is not compiled – which makes sense :)

if i set `compile: true` the export does not complete but ends wit this error message:

```
✖ Failed export to /Users/ff/srctemp/verias24/public
{ TypeError: /Users/ff/srctemp/verias24/_archiv/node_modules/pug/examples/code.pug:12
    10| 
    11| ul#users
  > 12|   each user, name in users
    13|     // expands to if (user.isA == 'ferret')
    14|     if user.isA == 'ferret'
    15|       li(class='user-' + name) #{name} is just a ferret

Cannot read property 'length' of undefined
    at eval (eval at wrap (/Users/ff/srctemp/verias24/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:23:31)
    at eval (eval at wrap (/Users/ff/srctemp/verias24/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:76:4)
    at template (eval at wrap (/Users/ff/srctemp/verias24/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:78:48)
    at compile (/Users/ff/srctemp/verias24/node_modules/@pingy/accord/lib/adapters/pug/2.0.0-rc - 2.x.js:35:54)
    at compile (/Users/ff/srctemp/verias24/node_modules/@pingy/accord/lib/adapters/pug/2.0.0-rc - 2.x.js:21:17)
    at Pug._render (/Users/ff/srctemp/verias24/node_modules/@pingy/accord/lib/adapters/pug/2.0.0-rc - 2.x.js:33:14)
    at Pug.render (/Users/ff/srctemp/verias24/node_modules/@pingy/accord/lib/adapter_base.js:105:17)
    at continuation.then.source (/Users/ff/srctemp/verias24/node_modules/@pingy/compile/lib/baby-tolk.js:220:17)
    at tryCatchReject (/Users/ff/srctemp/verias24/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/ff/srctemp/verias24/node_modules/when/lib/makePromise.js:804:4)
  path: '/Users/ff/srctemp/verias24/_archiv/node_modules/pug/examples/code.pug' }
⠸ Compiling cli.js
``

**Comment by filtercake** [comment]
this is my workaround for now:

`manual_export.sh`:

```
rm -rf manual_export
mkdir manual_export
cp *.html manual_export/
cp -r assets/ manual_export/assets/
cp -r icons/ manual_export/scripts/
cp -r img/ manual_export/scripts/
cp -r scripts/ manual_export/scripts/
mkdir manual_export/styles
node-sass styles/main.scss > manual_export/styles/main.css
cp AUTH manual_export/
cp CNAME manual_export/
```

**Comment by davej** [comment]
It looks from the traceback that you have an `_archiv` folder in the root of your site with `node_modules` inside it. Looks like that might be causing your issues. You can either delete it or add it to your exclusions.

Does that resolve the issue for you?

**Comment by davej** [comment]
By the way, if you want to include all descendant `node_modules` folders then you can change the exclusion path to `"**/node_modules"`.

**Comment by filtercake** [comment]
> It looks from the traceback that you have an `_archiv`

ugh :/ of course

thx!
